name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 步骤 1：获取代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤 2：设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 步骤 3：构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t devone930/demop:$GITHUB_SHA .

      # 步骤 4：登录 Docker Hub（如果需要推送到 Docker Hub）
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 步骤 5：推送 Docker 镜像
      - name: Push Docker image
        run: |
          docker push devone930/demo:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build  # 等待 build 任务完成

    steps:
      # 步骤 1：获取代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤 2：设置 kubectl（用于与 Kubernetes 交互）
      - name: Set up kubectl
        uses: actions/setup-kubectl@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}  # 使用 GitHub Secrets 中存储的 kubeconfig

      # 步骤 3：部署到 Kubernetes 集群
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl set image deployment/my-app my-app=my-app:$GITHUB_SHA  # 更新部署中的 Docker 镜像
